name: flappy_dash_ce
description: 'A Flappy Bird clone with a custom videogame engine'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
    sdk: ^3.5.4

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    logger: ^2.5.0
    shared_preferences: ^2.5.3
    audioplayers: ^6.4.0
    vibration: ^3.1.3

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/sprites/
        - assets/sprites/dash/
        - assets/sounds/
        - assets/images/
    fonts:
        - family: FlappyBirdy
          fonts:
              - asset: assets/fonts/flappybirdy/flappy-font.ttf
